export const refs = {
  categoriesList: document.querySelector('.categories'),
  productsList: document.querySelector('.products'),
  notFound: document.querySelector('.not-found'),
  modal: document.querySelector('.modal'),
  modalCloseBtn: document.querySelector('.modal__close-btn'),
  modalProduct: document.querySelector('.modal-product'),
  searchForm: document.querySelector('.search-form'),
  searchFormBtn: document.querySelector('.search-form__btn'),
  searchFormClearButton: document.querySelector('.search-form__btn-clear'),
  addToCartBtn: document.querySelector('.modal-product__btn--cart'),
  loader: document.querySelector('.loader'),
  wishList: document.querySelector('.modal-product__btn--wishlist'),
  cartCount: document.querySelector('[data-cart-count]'),
  wishlistCount: document.querySelector('[data-wishlist-count]'),
  addToWishlistBtn: document.querySelector('.modal-product__btn--wishlist'),
  loadMoreBtn: document.querySelector('.load-more-btn'),
};
